spring:
  datasource:
    url: "jdbc:h2:mem:db_eboutique"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: ""
  jpa:
      show-sql: "true"
      properties:
        hibernate:
          enable_lazy_load_no_trans: "true"
  h2:
      console:
          enabled: "true"
          path: "/h2-console"
