# Datasource
spring:
    datasource:
        url: "jdbc:h2:mem:db_produit"
        driverClassName: "org.h2.Driver"
        username: "sa"
        password: ""
    jpa:
        database-platform: "org.hibernate.dialect.H2Dialect"
        properties: 
            hibernate:
                enable_lazy_load_no_trans: "true"
    jackson:
        serialization:
            fail-on-empty-beans: "false"
    h2:
        console:
            enabled: "true"
            path: "/h2-console"