spring:
  datasource:
    url: "jdbc:h2:mem:db_m2hc"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: ""
  jpa:
      show-sql: "true"
  h2:
      console:
          enabled: "true"
          path: "/h2-console"