spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/db_boutique"
    username: "me"
    password: "me"
    driverClassName: "com.mysql.jdbc.Driver"
  jpa:
    show-sql: "true"
    generate-ddl: "true"
    hibernate:
      ddl-auto: "create"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"  